<div class="section section5 ft_gmarket">
    <div class="size">
        <span class="sec5_txt">
            <img src="img/sec-img4.png" class="pc">
            <img src="img/mo-sec-img4_1.png" class="mo">
        </span>
        <div class="cont cont1 graph_wrap">
            <div class="box_col_w col_wrap col2 clear">
                <div class="box_col">
                    <div class="box_tit">
                        <h4>동일 직렬/지역 참여자 총점 분포</h4>
                    </div>
                    <div class="box_wrap box_wrap1">
                        <div class="donut_graph donut_graph1 clear">
                            <div class="box">
                                <canvas id="p_subject1" width="198" height="198"
                                    style="display: block; box-sizing: border-box; height: 198px; width: 198px;"></canvas>
                            </div>
                            <div class="label_list">
                                <ul>
                                    <li class="li1">0 ~ 20점</li>
                                    <li class="li2">22.5 ~ 40점</li>
                                    <li class="li3">42.5 ~ 60점</li>
                                    <li class="li4">62.5 ~ 80점</li>
                                    <li class="li5">82.5 ~ 100점</li>
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>
                
                <div class="box_col">
                    <div class="box_tit">
                        <h4>모의고사 참여자 전체 총점 분포</h4>
                    </div>
                    <div class="box_wrap box_wrap1">
                        <div class="donut_graph donut_graph2 clear">
                            <div class="box">
                                <canvas id="p_subject2" width="198" height="198"
                                    style="display: block; box-sizing: border-box; height: 198px; width: 198px;"></canvas>
                            </div>
                            <div class="label_list">
                                <ul>
                                    <li class="li1">0 ~ 20점</li>
                                    <li class="li2">22.5 ~ 40점</li>
                                    <li class="li3">42.5 ~ 60점</li>
                                    <li class="li4">62.5 ~ 80점</li>
                                    <li class="li5">82.5 ~ 100점</li>
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <span class="sec5_txt">
                <img src="img/sec-img5.png" class="pc">
                <img src="img/mo-sec-img4_2.png" class="mo">
            </span>
        </div>
        <div class="cont cont2 graph_wrap">
            <div class="box_col_w col_wrap col2 clear">
                <div class="box_col">
                    <div class="box_tit">
                        <h4>형사법</h4>
                    </div>
                    <div class="box_wrap box_wrap1">
                        <div class="donut_graph donut_graph1 clear">
                            <div class="box">
                                <canvas id="p_subject3" width="198" height="198"
                                    style="display: block; box-sizing: border-box; height: 198px; width: 198px;"></canvas>
                            </div>
                            <div class="label_list">
                                <ul>
                                    <li class="li1">0 ~ 20점</li>
                                    <li class="li2">22.5 ~ 40점</li>
                                    <li class="li3">42.5 ~ 60점</li>
                                    <li class="li4">62.5 ~ 80점</li>
                                    <li class="li5">82.5 ~ 100점</li>
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="box_col">
                    <div class="box_tit">
                        <h4>형사법</h4>
                    </div>
                    <div class="box_wrap box_wrap1">
                        <div class="donut_graph donut_graph2 clear">
                            <div class="box">
                                <canvas id="p_subject4" width="198" height="198"
                                    style="display: block; box-sizing: border-box; height: 198px; width: 198px;"></canvas>
                            </div>
                            <div class="label_list">
                                <ul>
                                    <li class="li1">0 ~ 20점</li>
                                    <li class="li2">22.5 ~ 40점</li>
                                    <li class="li3">42.5 ~ 60점</li>
                                    <li class="li4">62.5 ~ 80점</li>
                                    <li class="li5">82.5 ~ 100점</li>
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <span class="sec5_txt">
                <img src="img/sec-img6.png" class="pc">
                <img src="img/mo-sec-img4_3.png" class="mo">
            </span>
        </div>
        <div class="cont cont3 graph_wrap">
            <div id="caseRank" class="box_area">
                <div class="box_wr active">
                    <div class="box_top">
                        <div class="box_scroll">
                            <div class="box_wrap">
                                <div class="tb_wrap">
                                    <table class="tb_st1">
                                        <caption>과목별 오답 랭킹</caption>
                                        <colgroup>
                                            <col width="11.35%">
                                            <col width="11.35%">
                                            <col width="11.35%">
                                            <col width="16.4875%">
                                            <col width="16.4875%">
                                            <col width="16.4875%">
                                            <col width="16.4875%">
                                        </colgroup>
                                        <thead>
                                            <tr>
                                                <th rowspan="2">오답 순위</th>
                                                <th rowspan="2">문제 번호</th>
                                                <th rowspan="2">정답</th>
                                                <th colspan="4" class="bd_btm">보기 선택률</th>
                                            </tr>
                                            <tr class="num">
                                                <th>
                                                    <span>1</span>
                                                </th>
                                                <th>
                                                    <span>2</span>
                                                </th>
                                                <th>
                                                    <span>3</span>
                                                </th>
                                                <th>
                                                    <span>4</span>
                                                </th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                            <tr>
                                                <td>1</td>
                                                <td>17</td>
                                                <td>3</td>
                                                <td>72.3%</td>
                                                <td>3.17%</td>
                                                <td>22.43%</td>
                                                <td>2.11%</td>
                                            </tr>
                                            <tr>
                                                <td>2</td>
                                                <td>19</td>
                                                <td>1</td>
                                                <td>40.11%</td>
                                                <td>41.95%</td>
                                                <td>14.78%</td>
                                                <td>3.17%</td>
                                            </tr>
                                            <tr>
                                                <td>3</td>
                                                <td>8</td>
                                                <td>3</td>
                                                <td>5.54%</td>
                                                <td>36.41%</td>
                                                <td>48.28%</td>
                                                <td>9.76%</td>
                                            </tr>
                                            <tr>
                                                <td>4</td>
                                                <td>20</td>
                                                <td>2</td>
                                                <td>21.11%</td>
                                                <td>51.98%</td>
                                                <td>4.22%</td>
                                                <td>22.69%</td>
                                            </tr>
                                            <tr>
                                                <td>5</td>
                                                <td>3</td>
                                                <td>2</td>
                                                <td>14.51%</td>
                                                <td>55.15%</td>
                                                <td>6.33%</td>
                                                <td>24.01%</td>
                                            </tr>
                                            <tr>
                                                <td>6</td>
                                                <td>13</td>
                                                <td>4</td>
                                                <td>4.48%</td>
                                                <td>23.22%</td>
                                                <td>16.36%</td>
                                                <td>61.48%</td>
                                            </tr>
                                            <tr>
                                                <td>7</td>
                                                <td>10</td>
                                                <td>4</td>
                                                <td>17.68%</td>
                                                <td>8.18%</td>
                                                <td>12.66%</td>
                                                <td>61.48%</td>
                                            </tr>
                                            <tr>
                                                <td>8</td>
                                                <td>2</td>
                                                <td>4</td>
                                                <td>2.11%</td>
                                                <td>6.07%</td>
                                                <td>24.8%</td>
                                                <td>67.02%</td>
                                            </tr>
                                            <tr>
                                                <td>9</td>
                                                <td>7</td>
                                                <td>1</td>
                                                <td>69.39%</td>
                                                <td>6.07%</td>
                                                <td>7.92%</td>
                                                <td>16.62%</td>
                                            </tr>
                                            <tr>
                                                <td>10</td>
                                                <td>1</td>
                                                <td>3</td>
                                                <td>4.49%</td>
                                                <td>13.19%</td>
                                                <td>72.3%</td>
                                                <td>10.03%</td>
                                            </tr>
                                            <tr>
                                                <td>11</td>
                                                <td>6</td>
                                                <td>3</td>
                                                <td>4.49%</td>
                                                <td>5.8%</td>
                                                <td>72.56%</td>
                                                <td>17.15%</td>
                                            </tr>
                                        </tbody>
                                    </table>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="cont cont4">
            <img src="img/sec-img7.png" class="pc">
            <img src="img/mo-sec-img4_4.png" class="mo">
        </div>
    </div>
</div>

<script type="text/javascript">

    //동일 직렬/지역 참여자 총점 분포
    var s_balance1 = [0, 5, 25, 65, 5];

    const p_subject1 = document.getElementById('p_subject1').getContext('2d');
    const p_subject1_chart = new Chart(p_subject1, {
        type: 'doughnut',
        data: {
            labels: ['0 ~ 50점', '50.5 ~ 100점', '100.5 ~ 150점', '150.5 ~ 200점', '200.5 ~ 250점'],
            datasets: [{
                data: s_balance1,
                backgroundColor: [
                    '#b0baca',
                    '#79baed',
                    '#7ad5d2',
                    '#ffc62c',
                    '#ff6766'
                ],
                hoverBackgroundColor: [
                    '#b0baca',
                    '#79baed',
                    '#7ad5d2',
                    '#ffc62c',
                    '#ff6766'
                ],
                borderWidth: 1
            }]
        },
        options: {
            legend: {
                display: false
            },
            plugins: {
                legend: {
                    display: false
                }
            }
        }
    });

    var s_balance2 = [0, 2, 18, 80, 0];

    const p_subject2 = document.getElementById('p_subject2').getContext('2d');
    const p_subject2_chart = new Chart(p_subject2, {
        type: 'doughnut',
        data: {
            labels: ['0 ~ 50점', '50.5 ~ 100점', '100.5 ~ 150점', '150.5 ~ 200점', '200.5 ~ 250점'],
            datasets: [{
                data: s_balance2,
                backgroundColor: [
                    '#b0baca',
                    '#79baed',
                    '#7ad5d2',
                    '#ffc62c',
                    '#ff6766'
                ],
                hoverBackgroundColor: [
                    '#b0baca',
                    '#79baed',
                    '#7ad5d2',
                    '#ffc62c',
                    '#ff6766'
                ],
                borderWidth: 1
            }]
        },
        options: {
            legend: {
                display: false
            },
            plugins: {
                legend: {
                    display: false
                }
            }
        }
    });


    //형사법
    var s_balance3 = [0, 7, 20, 49, 4];

    const p_subject3 = document.getElementById('p_subject3').getContext('2d');
    const p_subject3_chart = new Chart(p_subject3, {
        type: 'doughnut',
        data: {
            labels: ['0 ~ 50점', '50.5 ~ 100점', '100.5 ~ 150점', '150.5 ~ 200점', '200.5 ~ 250점'],
            datasets: [{
                data: s_balance3,
                backgroundColor: [
                    '#b0baca',
                    '#79baed',
                    '#7ad5d2',
                    '#ffc62c',
                    '#ff6766'
                ],
                hoverBackgroundColor: [
                    '#b0baca',
                    '#79baed',
                    '#7ad5d2',
                    '#ffc62c',
                    '#ff6766'
                ],
                borderWidth: 1
            }]
        },
        options: {
            legend: {
                display: false
            },
            plugins: {
                legend: {
                    display: false
                }
            }
        }
    });

    var s_balance4 = [0, 7, 20, 49, 4];

    const p_subject4 = document.getElementById('p_subject4').getContext('2d');
    const p_subject4_chart = new Chart(p_subject4, {
        type: 'doughnut',
        data: {
            labels: ['0 ~ 50점', '50.5 ~ 100점', '100.5 ~ 150점', '150.5 ~ 200점', '200.5 ~ 250점'],
            datasets: [{
                data: s_balance4,
                backgroundColor: [
                    '#b0baca',
                    '#79baed',
                    '#7ad5d2',
                    '#ffc62c',
                    '#ff6766'
                ],
                hoverBackgroundColor: [
                    '#b0baca',
                    '#79baed',
                    '#7ad5d2',
                    '#ffc62c',
                    '#ff6766'
                ],
                borderWidth: 1
            }]
        },
        options: {
            legend: {
                display: false
            },
            plugins: {
                legend: {
                    display: false
                }
            }
        }
    });
</script>

